-- MySQL Script generated by MySQL Workbench
-- 02/20/15 21:22:41
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema IT112_Exercise1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IT112_Exercise1` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `IT112_Exercise1` ;

-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(32) NULL,
  `region_description` VARCHAR(32) NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_code` VARCHAR(32) NULL,
  `province_description` VARCHAR(32) NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`province_id`, `region_id`),
  INDEX `fk_province_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_province_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `IT112_Exercise1`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_code` VARCHAR(32) NULL,
  `city_description` VARCHAR(32) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`, `province_id`),
  INDEX `fk_city_province2_idx` (`province_id` ASC),
  CONSTRAINT `fk_city_province2`
    FOREIGN KEY (`province_id`)
    REFERENCES `IT112_Exercise1`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`region`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`region` (
  `region_id` INT NOT NULL AUTO_INCREMENT,
  `region_code` VARCHAR(32) NULL,
  `region_description` VARCHAR(32) NULL,
  PRIMARY KEY (`region_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`province` (
  `province_id` INT NOT NULL AUTO_INCREMENT,
  `province_code` VARCHAR(32) NULL,
  `province_description` VARCHAR(32) NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`province_id`, `region_id`),
  INDEX `fk_province_region1_idx` (`region_id` ASC),
  CONSTRAINT `fk_province_region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `IT112_Exercise1`.`region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IT112_Exercise1`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IT112_Exercise1`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_code` VARCHAR(32) NULL,
  `city_description` VARCHAR(32) NULL,
  `province_id` INT NOT NULL,
  PRIMARY KEY (`city_id`, `province_id`),
  INDEX `fk_city_province2_idx` (`province_id` ASC),
  CONSTRAINT `fk_city_province2`
    FOREIGN KEY (`province_id`)
    REFERENCES `IT112_Exercise1`.`province` (`province_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
