-- MySQL Script generated by MySQL Workbench
-- 03/08/15 22:29:59
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema abesamis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `abesamis` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `abesamis` ;

-- -----------------------------------------------------
-- Table `abesamis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` SMALLINT(6) NOT NULL DEFAULT 10,
  `status` SMALLINT(6) NOT NULL DEFAULT 10,
  `created_at` INT(11) NOT NULL,
  `updated_at` INT(11) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_code` VARCHAR(45) NOT NULL,
  `city_name` VARCHAR(45) NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_code_UNIQUE` (`city_code` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`contact_lens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`contact_lens` (
  `contact_lens_id` INT NOT NULL AUTO_INCREMENT,
  `contact_lens_value` VARCHAR(45) NOT NULL,
  `contact_lens_description` VARCHAR(45) NULL,
  PRIMARY KEY (`contact_lens_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`patient`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`patient` (
  `patient_id` INT NOT NULL AUTO_INCREMENT,
  `patient_lname` VARCHAR(45) NOT NULL,
  `patient_fname` VARCHAR(45) NOT NULL,
  `patient_mname` VARCHAR(45) NULL,
  `patient_birthday` DATE NOT NULL,
  `patient_sex` VARCHAR(1) NOT NULL,
  `patient_facebook` VARCHAR(45) NULL,
  `patient_landline` VARCHAR(45) NULL,
  `patient_cel1` VARCHAR(45) NOT NULL,
  `patient_cel2` VARCHAR(45) NULL,
  `patient_company` VARCHAR(45) NULL,
  `patient_add_work` VARCHAR(45) NULL,
  `patient_contact_work` VARCHAR(45) NULL,
  `user_id` INT NOT NULL,
  `patient_add_street` VARCHAR(45) NOT NULL,
  `patient_add_town_subd_vill` VARCHAR(150) NOT NULL,
  `patient_add_number` VARCHAR(45) NOT NULL,
  `patient_add_city_id` INT NOT NULL,
  `patientl_allergies` LONGTEXT NOT NULL,
  `patient_medications` LONGTEXT NOT NULL,
  `patient_treatments` LONGTEXT NOT NULL,
  `patient_pregnant` VARCHAR(1) NOT NULL,
  `patient_glasses` VARCHAR(1) NOT NULL,
  `patient_glasses_age` INT NULL,
  `patient_contact_lens` VARCHAR(1) NOT NULL,
  `patient_contact_lens_age` INT NULL,
  `contact_lens_id` INT NOT NULL,
  PRIMARY KEY (`patient_id`),
  INDEX `fk_patient_user1_idx` (`user_id` ASC),
  INDEX `fk_patient_city1_idx` (`patient_add_city_id` ASC),
  INDEX `fk_patient_contact_lens1_idx` (`contact_lens_id` ASC),
  CONSTRAINT `fk_patient_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `abesamis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_city1`
    FOREIGN KEY (`patient_add_city_id`)
    REFERENCES `abesamis`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_contact_lens1`
    FOREIGN KEY (`contact_lens_id`)
    REFERENCES `abesamis`.`contact_lens` (`contact_lens_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`employee` (
  `employee_id` INT NOT NULL AUTO_INCREMENT,
  `employee_lname` VARCHAR(45) NOT NULL,
  `employee_fname` VARCHAR(45) NOT NULL,
  `employee_mname` VARCHAR(45) NULL,
  `employee_birthday` DATE NOT NULL,
  `employee_sex` VARCHAR(1) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`employee_id`),
  INDEX `fk_employee_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_employee_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `abesamis`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`insurance` (
  `insurance_id` INT NOT NULL AUTO_INCREMENT,
  `insurance_name` VARCHAR(45) NOT NULL,
  `insurance_description` VARCHAR(45) NULL,
  `insurance_percentage` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`insurance_id`),
  UNIQUE INDEX `insurance_name_UNIQUE` (`insurance_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`discount` (
  `discount_id` INT NOT NULL AUTO_INCREMENT,
  `discount_name` VARCHAR(45) NOT NULL,
  `discount_description` VARCHAR(45) NULL,
  PRIMARY KEY (`discount_id`),
  UNIQUE INDEX `discount_name_UNIQUE` (`discount_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`record` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `patient_signature` LONGBLOB NOT NULL,
  `agreed_date` DATETIME NOT NULL,
  `employee_signature` LONGBLOB NOT NULL,
  `employee_id` INT NOT NULL,
  `insurance_id` INT NULL,
  `discount_id` INT NULL,
  `complaints` VARCHAR(300) NULL,
  PRIMARY KEY (`record_id`, `patient_id`),
  INDEX `fk_record_patient_idx` (`patient_id` ASC),
  INDEX `fk_record_employee1_idx` (`employee_id` ASC),
  INDEX `fk_record_insurance1_idx` (`insurance_id` ASC),
  INDEX `fk_record_discount1_idx` (`discount_id` ASC),
  CONSTRAINT `fk_record_patient`
    FOREIGN KEY (`patient_id`)
    REFERENCES `abesamis`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `abesamis`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_insurance1`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `abesamis`.`insurance` (`insurance_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_discount1`
    FOREIGN KEY (`discount_id`)
    REFERENCES `abesamis`.`discount` (`discount_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`family_disease`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`family_disease` (
  `family_disease_id` INT NOT NULL AUTO_INCREMENT,
  `family_disease_name` VARCHAR(45) NOT NULL,
  `family_disease_description` VARCHAR(45) NULL,
  PRIMARY KEY (`family_disease_id`),
  UNIQUE INDEX `family_disease_name_UNIQUE` (`family_disease_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`relationship`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`relationship` (
  `relationship_id` INT NOT NULL AUTO_INCREMENT,
  `relationship_name` VARCHAR(45) NOT NULL,
  `relationship_description` VARCHAR(45) NULL,
  PRIMARY KEY (`relationship_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`history_family`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`history_family` (
  `patient_id` INT NOT NULL,
  `family_disease_id` INT NOT NULL,
  `relationship_id` INT NOT NULL,
  PRIMARY KEY (`patient_id`, `family_disease_id`),
  INDEX `fk_history_family_patient1_idx` (`patient_id` ASC),
  INDEX `fk_history_family_family_disease_list1_idx` (`family_disease_id` ASC),
  INDEX `fk_history_family_relationship1_idx` (`relationship_id` ASC),
  CONSTRAINT `fk_history_family_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `abesamis`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_family_family_disease_list1`
    FOREIGN KEY (`family_disease_id`)
    REFERENCES `abesamis`.`family_disease` (`family_disease_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_family_relationship1`
    FOREIGN KEY (`relationship_id`)
    REFERENCES `abesamis`.`relationship` (`relationship_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`sports` (
  `sports_id` INT NOT NULL AUTO_INCREMENT,
  `sports_name` VARCHAR(45) NOT NULL,
  `sports_description` VARCHAR(45) NULL,
  PRIMARY KEY (`sports_id`),
  UNIQUE INDEX `sports_name_UNIQUE` (`sports_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`history_sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`history_sports` (
  `sports_id` INT NOT NULL,
  `patient_id` INT NOT NULL,
  `history_value` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`sports_id`, `patient_id`),
  INDEX `fk_history_sports_sports1_idx` (`sports_id` ASC),
  INDEX `fk_history_sports_patient1_idx` (`patient_id` ASC),
  CONSTRAINT `fk_history_sports_sports1`
    FOREIGN KEY (`sports_id`)
    REFERENCES `abesamis`.`sports` (`sports_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_history_sports_patient1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `abesamis`.`patient` (`patient_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`instruction` (
  `instruction_id` INT NOT NULL AUTO_INCREMENT,
  `instruction_name` VARCHAR(45) NOT NULL,
  `instruction_description` VARCHAR(45) NULL,
  PRIMARY KEY (`instruction_id`),
  UNIQUE INDEX `instruction_name_UNIQUE` (`instruction_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`design`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`design` (
  `design_id` INT NOT NULL AUTO_INCREMENT,
  `design_name` VARCHAR(45) NOT NULL,
  `design_description` VARCHAR(45) NULL,
  PRIMARY KEY (`design_id`),
  UNIQUE INDEX `design_name_UNIQUE` (`design_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`material` (
  `material_id` INT NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(45) NOT NULL,
  `material_description` VARCHAR(45) NULL,
  UNIQUE INDEX `material_name_UNIQUE` (`material_name` ASC),
  PRIMARY KEY (`material_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`prescription` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `dist_od_sph` DECIMAL(5,2) NOT NULL,
  `dist_od_prism` DECIMAL(5,2) NOT NULL,
  `dist_od_cyl` DECIMAL(5,2) NOT NULL,
  `dist_od_axis` DECIMAL(5,2) NOT NULL,
  `dist_od_add` DECIMAL(5,2) NOT NULL,
  `dist_os_sph` DECIMAL(5,2) NOT NULL,
  `dist_os_prism` DECIMAL(5,2) NOT NULL,
  `dist_os_cyl` DECIMAL(5,2) NOT NULL,
  `dist_os_axis` DECIMAL(5,2) NOT NULL,
  `dist_os_add` DECIMAL(5,2) NOT NULL,
  `near_od_sph` DECIMAL(5,2) NOT NULL,
  `near_od_prism` DECIMAL(5,2) NOT NULL,
  `near_od_cyl` DECIMAL(5,2) NOT NULL,
  `near_od_axis` DECIMAL(5,2) NOT NULL,
  `near_od_add` DECIMAL(5,2) NOT NULL,
  `near_os_sph` DECIMAL(5,2) NOT NULL,
  `near_os_prism` DECIMAL(5,2) NOT NULL,
  `near_os_cyl` DECIMAL(5,2) NOT NULL,
  `near_os_axis` DECIMAL(5,2) NOT NULL,
  `near_os_add` DECIMAL(5,2) NOT NULL,
  `instruction_id` INT NOT NULL,
  `od_bc` DECIMAL(5,2) NOT NULL,
  `od_diam` DECIMAL(5,2) NOT NULL,
  `od_power` DECIMAL(5,2) NOT NULL,
  `od_ct` DECIMAL(5,2) NOT NULL,
  `od_color` VARCHAR(45) NOT NULL,
  `os_bc` DECIMAL(5,2) NOT NULL,
  `os_diam` DECIMAL(5,2) NOT NULL,
  `os_power` DECIMAL(5,2) NOT NULL,
  `os_ct` DECIMAL(5,2) NOT NULL,
  `os_color` VARCHAR(45) NOT NULL,
  `design_id` INT NOT NULL,
  `material_id` INT NOT NULL,
  PRIMARY KEY (`record_id`, `design_id`, `material_id`),
  INDEX `fk_presc_spectacle_instruction1_idx` (`instruction_id` ASC),
  INDEX `fk_presc_spectacle_design1_idx` (`design_id` ASC),
  INDEX `fk_presc_spectacle_material1_idx` (`material_id` ASC),
  CONSTRAINT `fk_spectacle_record1`
    FOREIGN KEY (`record_id`)
    REFERENCES `abesamis`.`record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presc_spectacle_instruction1`
    FOREIGN KEY (`instruction_id`)
    REFERENCES `abesamis`.`instruction` (`instruction_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presc_spectacle_design1`
    FOREIGN KEY (`design_id`)
    REFERENCES `abesamis`.`design` (`design_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_presc_spectacle_material1`
    FOREIGN KEY (`material_id`)
    REFERENCES `abesamis`.`material` (`material_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`acuity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`acuity` (
  `acuity_id` INT NOT NULL AUTO_INCREMENT,
  `acuity_name` VARCHAR(45) NOT NULL,
  `acuity_description` VARCHAR(45) NULL,
  PRIMARY KEY (`acuity_id`),
  UNIQUE INDEX `acuity_name_UNIQUE` (`acuity_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`eoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`eoms` (
  `eoms_id` INT NOT NULL AUTO_INCREMENT,
  `eoms_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`eoms_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`evaluation` (
  `record_id` INT NOT NULL,
  `v_d_od_sc` INT NOT NULL,
  `v_d_od_cc` INT NOT NULL,
  `v_d_od_ph` INT NOT NULL,
  `v_n_od_sc` INT NOT NULL,
  `v_n_od_cc` INT NOT NULL,
  `v_d_os_sc` INT NOT NULL,
  `v_d_os_cc` INT NOT NULL,
  `v_d_os_ph` INT NOT NULL,
  `v_n_os_sc` INT NOT NULL,
  `v_n_os_cc` INT NOT NULL,
  `v_d_ou_sc` INT NOT NULL,
  `v_d_ou_cc` INT NOT NULL,
  `v_d_ou_ph` INT NOT NULL,
  `v_n_ou_sc` INT NOT NULL,
  `v_n_ou_cc` INT NOT NULL,
  `r_a_od` DECIMAL(5,2) NOT NULL,
  `r_a_os` DECIMAL(5,2) NOT NULL,
  `r_m_od` DECIMAL(5,2) NOT NULL,
  `r_m_os` DECIMAL(5,2) NOT NULL,
  `r_c_od` DECIMAL(5,2) NOT NULL,
  `r_c_os` DECIMAL(5,2) NOT NULL,
  `r_o_od` DECIMAL(5,2) NOT NULL,
  `r_o_os` DECIMAL(5,2) NOT NULL,
  `r_w_od` DECIMAL(5,2) NOT NULL,
  `r_w_os` DECIMAL(5,2) NOT NULL,
  `k_h_od` DECIMAL(5,2) NOT NULL,
  `k_h_os` DECIMAL(5,2) NOT NULL,
  `k_v_od` DECIMAL(5,2) NOT NULL,
  `k_v_os` DECIMAL(5,2) NOT NULL,
  `k_c_od` DECIMAL(5,2) NOT NULL,
  `k_c_os` DECIMAL(5,2) NOT NULL,
  `t_od1` DECIMAL(5,2) NOT NULL,
  `t_od2` DECIMAL(5,2) NOT NULL,
  `t_os1` DECIMAL(5,2) NOT NULL,
  `t_os2` DECIMAL(5,2) NOT NULL,
  `bp_s` INT NOT NULL,
  `bp_d` INT NOT NULL,
  `p_d_l` INT NOT NULL,
  `p_d_v` INT NOT NULL,
  `p_n_l` INT NOT NULL,
  `p_n_v` INT NOT NULL,
  `p_d_bi` INT NOT NULL,
  `p_d_lbu` INT NOT NULL,
  `p_n_bi` INT NOT NULL,
  `p_n_lbu` INT NOT NULL,
  `p_d_bo` INT NOT NULL,
  `p_d_lbo` INT NOT NULL,
  `p_n_bo` INT NOT NULL,
  `p_n_lbo` INT NOT NULL,
  `pupil_p_od` VARCHAR(1) NOT NULL,
  `pupil_p_os` VARCHAR(1) NOT NULL,
  `pupil_s_od` VARCHAR(1) NOT NULL,
  `pupil_s_os` VARCHAR(1) NOT NULL,
  `pupil_rapd` VARCHAR(1) NOT NULL,
  `eoms_id` INT NOT NULL,
  `m_dominant` VARCHAR(45) NOT NULL,
  `m_other` VARCHAR(45) NOT NULL,
  `m_p_accom` INT NOT NULL,
  `m_a_accom` INT NOT NULL,
  `m_p_conver` INT NOT NULL,
  `color_test` VARCHAR(45) NOT NULL,
  `stereo/w4d` VARCHAR(45) NOT NULL,
  `confrontation/avf` VARCHAR(45) NOT NULL,
  `gross_exam` LONGTEXT NOT NULL,
  `ee_lids_od` VARCHAR(45) NOT NULL,
  `ee_lids_os` VARCHAR(45) NOT NULL,
  `ee_c_od` VARCHAR(45) NOT NULL,
  `ee_c_os` VARCHAR(45) NOT NULL,
  `ee_d_od` VARCHAR(45) NOT NULL,
  `ee_d_os` VARCHAR(45) NOT NULL,
  `ee_l_od` VARCHAR(45) NOT NULL,
  `ee_l_os` VARCHAR(45) NOT NULL,
  `ee_t_od` VARCHAR(45) NOT NULL,
  `ee_t_os` VARCHAR(45) NOT NULL,
  `ee_s_od` VARCHAR(45) NOT NULL,
  `ee_s_os` VARCHAR(45) NOT NULL,
  `ee_od` LONGBLOB NOT NULL,
  `ee_os` LONGBLOB NOT NULL,
  `se_c_od` VARCHAR(45) NOT NULL,
  `se_c_os` VARCHAR(45) NOT NULL,
  `se_a_od` VARCHAR(45) NOT NULL,
  `se_a_os` VARCHAR(45) NOT NULL,
  `se_i_od` VARCHAR(45) NOT NULL,
  `se_i_os` VARCHAR(45) NOT NULL,
  `se_l_od` VARCHAR(45) NOT NULL,
  `se_l_os` VARCHAR(45) NOT NULL,
  `se_v_od` VARCHAR(45) NOT NULL,
  `se_v_os` VARCHAR(45) NOT NULL,
  `se_od` LONGBLOB NOT NULL,
  `se_os` LONGBLOB NOT NULL,
  `f_me_od` INT NOT NULL,
  `f_me_os` INT NOT NULL,
  `f_d_od` INT NOT NULL,
  `f_d_os` INT NOT NULL,
  `f_c_od` INT NOT NULL,
  `f_c_os` INT NOT NULL,
  `f_v_od` VARCHAR(45) NOT NULL,
  `f_v_os` VARCHAR(45) NOT NULL,
  `f_p_od` VARCHAR(45) NOT NULL,
  `f_p_os` VARCHAR(45) NOT NULL,
  `f_ma_od` VARCHAR(45) NOT NULL,
  `f_m_os` VARCHAR(45) NOT NULL,
  `g_od1` LONGBLOB NOT NULL,
  `g_os1` LONGBLOB NOT NULL,
  `g_od2` LONGBLOB NOT NULL,
  `g_os2` LONGBLOB NOT NULL,
  `d_od` LONGBLOB NOT NULL,
  `d_os` LONGBLOB NOT NULL,
  `diagnostic_result` LONGTEXT NOT NULL,
  `management` LONGTEXT NOT NULL,
  `plan_TCB` LONGTEXT NOT NULL,
  `plan_next_visit` DATE NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`record_id`),
  INDEX `fk_evaluation_record1_idx` (`record_id` ASC),
  INDEX `fk_evaluation_eoms1_idx` (`eoms_id` ASC),
  INDEX `fk_evaluation_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_evaluation_record1`
    FOREIGN KEY (`record_id`)
    REFERENCES `abesamis`.`record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_eoms1`
    FOREIGN KEY (`eoms_id`)
    REFERENCES `abesamis`.`eoms` (`eoms_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `abesamis`.`employee` (`employee_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`migration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`migration` (
  `version` VARCHAR(180) NOT NULL,
  `apply_time` INT(11) NULL,
  PRIMARY KEY (`version`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`lens_design`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`lens_design` (
  `design_id` INT NOT NULL,
  `design_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`design_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `abesamis`.`lens_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `abesamis`.`lens_material` (
  `material_id` INT NOT NULL AUTO_INCREMENT,
  `material_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`material_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
