-- MySQL Script generated by MySQL Workbench
-- 05/04/15 17:25:08
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ecpms-sd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecpms-sd` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ecpms-sd` ;

-- -----------------------------------------------------
-- Table `ecpms-sd`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `auth_key` VARCHAR(32) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` SMALLINT(6) NOT NULL DEFAULT 10,
  `status` SMALLINT(6) NOT NULL DEFAULT 10,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`record` (
  `record_id` INT NOT NULL AUTO_INCREMENT,
  `patient_id` INT NOT NULL,
  `employee_id` INT NOT NULL,
  `patient_signature` LONGBLOB NULL,
  `agreed_date` DATETIME NULL,
  `employee_signature` LONGBLOB NULL,
  `complaints` LONGTEXT NULL,
  PRIMARY KEY (`record_id`),
  INDEX `fk_record_user2_idx` (`patient_id` ASC),
  INDEX `fk_record_user1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_record_user2`
    FOREIGN KEY (`patient_id`)
    REFERENCES `ecpms-sd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_user1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ecpms-sd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`insurance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`insurance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `insurance_name` VARCHAR(45) NOT NULL,
  `insurance_description` VARCHAR(45) NULL,
  `insurance_percentage` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `insurance_name_UNIQUE` (`insurance_name` ASC))
ENGINE = InnoDB;

INSERT INTO `insurance` (`id`, `insurance_name`, `insurance_percentage`) VALUES
(1, 'Maxicare', 0),
(2, 'Cocolife', 0),
(3, 'ValuCare', 0),
(4, 'Prudentialife', 0),
(5, 'AsianLife', 0),
(6, 'Medserve', 0),
(7, 'St. Patrick', 0),
(8, 'Philcare', 0),
(9, 'AA International', 0),
(10, 'Living Well', 0),
(11, 'SM Global Pinoy', 0),
(12, 'Walk-in', 0),
(13, 'Established Patient', 0),
(14, 'Others', 0);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`contact_lens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`contact_lens` (
  `contact_lens_id` INT NOT NULL AUTO_INCREMENT,
  `contact_lens_name` VARCHAR(45) NOT NULL,
  `contact_lens_description` VARCHAR(45) NULL,
  PRIMARY KEY (`contact_lens_id`))
ENGINE = InnoDB;

INSERT INTO `contact_lens` (`contact_lens_id`, `contact_lens_name`, `contact_lens_description`) VALUES
(1, 'Rigid', NULL),
(2, 'Soft', NULL),
(3, 'Other', NULL);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`city` (
  `city_id` INT NOT NULL AUTO_INCREMENT,
  `city_name` VARCHAR(45) NOT NULL,
  `city_code` INT NULL,
  PRIMARY KEY (`city_id`),
  UNIQUE INDEX `city_name_UNIQUE` (`city_name` ASC))
ENGINE = InnoDB;

INSERT INTO `city` (`city_id`, `city_name`, `city_code`) VALUES
(1, 'Makati', 1200),
(2, 'Pasay', 1300);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`eoms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`eoms` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `eoms_name` VARCHAR(45) NOT NULL,
  `eoms_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `eoms` (`id`, `eoms_name`) VALUES
(1, 'full_safe'),
(2, 'esophoria'),
(3, 'esotropia'),
(4, 'exotropia'),
(5, 'hyperphoria'),
(6, 'hypertropia'),
(7, 'hypophoria'),
(8, 'hypotropia'),
(9, 'cyclophoria'),
(10, 'cyclotropia');

-- -----------------------------------------------------
-- Table `ecpms-sd`.`wear_mode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`wear_mode` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `wear_mode_name` VARCHAR(45) NOT NULL,
  `wear_mode_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `wear_mode_name_UNIQUE` (`wear_mode_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`solutions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`solutions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `solutions_name` VARCHAR(45) NOT NULL,
  `solutions_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `solutions_name_UNIQUE` (`solutions_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`design`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`design` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `design_name` VARCHAR(45) NOT NULL,
  `design_description` VARCHAR(45) NULL,
  UNIQUE INDEX `design_name_UNIQUE` (`design_name` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `design` (`id`, `design_name`, `design_description`) VALUES
(1, 'CR39', NULL),
(2, 'Hi-index', NULL),
(3, 'Polycarb', NULL),
(4, 'Anti-UV', NULL),
(7, 'MC', NULL),
(8, 'Progressive', NULL),
(9, 'DV', NULL);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`instruction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`instruction` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `instruction_name` VARCHAR(45) NOT NULL,
  `instruction_description` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

INSERT INTO `instruction` (`id`, `instruction_name`, `instruction_description`) VALUES
(1, 'constant wear', NULL),
(2, 'far only', NULL),
(3, 'near only', NULL),
(4, 'intermediate', NULL);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`acuity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`acuity` (
  `acuity_id` INT NOT NULL AUTO_INCREMENT,
  `acuity_name` VARCHAR(45) NOT NULL,
  `acuity_description` VARCHAR(45) NULL,
  PRIMARY KEY (`acuity_id`),
  UNIQUE INDEX `acuity_name_UNIQUE` (`acuity_name` ASC))
ENGINE = InnoDB;

INSERT INTO `acuity` (`acuity_id`, `acuity_name`, `acuity_description`) VALUES
(1, 'NLP', NULL),
(2, 'LP', NULL),
(3, 'HM', NULL),
(4, '20/800', NULL),
(5, '20/400', NULL),
(6, '20/200', NULL),
(7, '20/100', NULL),
(8, '20/80', NULL),
(9, '20/60', NULL),
(10, '20/40', NULL),
(11, '20/30', NULL),
(12, '20/20', NULL),
(13, '20/15', NULL),
(14, '20/10', NULL);

-- -----------------------------------------------------
-- Table `ecpms-sd`.`patient_profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`patient_profile` (
  `user_id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `middlename` VARCHAR(255) NULL,
  `birthday` DATE NOT NULL,
  `gender` VARCHAR(1) NOT NULL,
  `city_id` INT NULL,
  `home_address` VARCHAR(255) NOT NULL,
  `company_address` VARCHAR(255) NULL,
  `company_name` VARCHAR(45) NULL,
  `cel` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `fb` VARCHAR(75) NULL,
  `sports` LONGTEXT NULL,
  INDEX `fk_user_city1_idx` (`city_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_city10`
    FOREIGN KEY (`city_id`)
    REFERENCES `ecpms-sd`.`city` (`city_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patient_profile_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecpms-sd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`medical_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`medical_history` (
  `user_id` INT NOT NULL,
  `allergies` LONGTEXT NULL,
  `medications` LONGTEXT NULL,
  `treatments` LONGTEXT NULL,
  `eyeglasses` VARCHAR(1) NOT NULL,
  `eyeglasses_age` VARCHAR(45) NULL,
  `contact_lens` VARCHAR(1) NOT NULL,
  `contact_lens_age` VARCHAR(45) NULL,
  `contact_lens_id` INT NULL,
  `comfortability` TINYINT(1) NULL,
  `blindness_grand` TINYINT(1) NOT NULL,
  `blindness_parents` TINYINT(1) NOT NULL,
  `blindness_siblings` TINYINT(1) NOT NULL,
  `blindness_children` TINYINT(1) NOT NULL,
  `cataracts_grand` TINYINT(1) NOT NULL,
  `cataracts_parents` TINYINT(1) NOT NULL,
  `cataracts_siblings` TINYINT(1) NOT NULL,
  `cataracts_children` TINYINT(1) NOT NULL,
  `crossed_eyes_grand` TINYINT(1) NOT NULL,
  `crossed_eyes_parents` TINYINT(1) NOT NULL,
  `crossed_eyes_siblings` TINYINT(1) NOT NULL,
  `crossed_eyes_children` TINYINT(1) NOT NULL,
  `glaucoma_grand` TINYINT(1) NOT NULL,
  `glaucoma_parents` TINYINT(1) NOT NULL,
  `glaucoma_siblings` TINYINT(1) NOT NULL,
  `glaucoma_children` TINYINT(1) NOT NULL,
  `macular_degeneration_grand` TINYINT(1) NOT NULL,
  `macular_degeneration_parents` TINYINT(1) NOT NULL,
  `macular_degeneration_siblings` TINYINT(1) NOT NULL,
  `macular_degeneration_children` TINYINT(1) NOT NULL,
  `retinal_detachment_grand` TINYINT(1) NOT NULL,
  `retinal_detachment_parents` TINYINT(1) NOT NULL,
  `retinal_detachment_siblings` TINYINT(1) NOT NULL,
  `retinal_detachment_children` TINYINT(1) NOT NULL,
  `arthritis_grand` TINYINT(1) NOT NULL,
  `arthritis_parents` TINYINT(1) NOT NULL,
  `arthritis_siblings` TINYINT(1) NOT NULL,
  `arthritis_children` TINYINT(1) NOT NULL,
  `cancer_grand` TINYINT(1) NOT NULL,
  `cancer_parents` TINYINT(1) NOT NULL,
  `cancer_siblings` TINYINT(1) NOT NULL,
  `cancer_children` TINYINT(1) NOT NULL,
  `diabetes_grand` TINYINT(1) NOT NULL,
  `diabetes_parents` TINYINT(1) NOT NULL,
  `diabetes_siblings` TINYINT(1) NOT NULL,
  `diabetes_children` TINYINT(1) NOT NULL,
  `heart_disease_grand` TINYINT(1) NOT NULL,
  `heart_disease_parents` TINYINT(1) NOT NULL,
  `heart_disease_siblings` TINYINT(1) NOT NULL,
  `heart_disease_children` TINYINT(1) NOT NULL,
  `high_blood_pressure_grand` TINYINT(1) NOT NULL,
  `high_blood_pressure_parents` TINYINT(1) NOT NULL,
  `high_blood_pressure_siblings` TINYINT(1) NOT NULL,
  `high_blood_pressure_children` TINYINT(1) NOT NULL,
  `kidney_disease_grand` TINYINT(1) NOT NULL,
  `kidney_disease_parents` TINYINT(1) NOT NULL,
  `kidney_disease_siblings` TINYINT(1) NOT NULL,
  `kidney_disease_children` TINYINT(1) NOT NULL,
  `lupus_grand` TINYINT(1) NOT NULL,
  `lupus_parents` TINYINT(1) NOT NULL,
  `lupus_siblings` TINYINT(1) NOT NULL,
  `lupus_children` TINYINT(1) NOT NULL,
  `thyroid_disease_grand` TINYINT(1) NOT NULL,
  `thyroid_disease_parents` TINYINT(1) NOT NULL,
  `thyroid_disease_siblings` TINYINT(1) NOT NULL,
  `thyroid_disease_children` TINYINT(1) NOT NULL,
  `others` LONGTEXT NULL,
  `headaches` TINYINT(1) NOT NULL,
  `migrains` TINYINT(1) NOT NULL,
  `seizures` TINYINT(1) NOT NULL,
  `loss_of_vision` TINYINT(1) NOT NULL,
  `blurred_vision` TINYINT(1) NOT NULL,
  `distorted_vision` TINYINT(1) NOT NULL,
  `loss_of_side_vision` TINYINT(1) NOT NULL,
  `double_vision` TINYINT(1) NOT NULL,
  `dryness_vision` TINYINT(1) NOT NULL,
  `mucous_discharge` TINYINT(1) NOT NULL,
  `redness` TINYINT(1) NOT NULL,
  `sandy_gritty_feeling` TINYINT(1) NOT NULL,
  `itching` TINYINT(1) NOT NULL,
  `burning` TINYINT(1) NOT NULL,
  `foreign_body_sensation` TINYINT(1) NOT NULL,
  `excess_tearing_watering` TINYINT(1) NOT NULL,
  `glare_light_sensitivity` TINYINT(1) NOT NULL,
  `eye_pain_soreness` TINYINT(1) NOT NULL,
  `chronic_infection_of_eye_or_lid` TINYINT(1) NOT NULL,
  `sties_chalazion` TINYINT(1) NOT NULL,
  `flashes_floaters_of_vision` TINYINT(1) NOT NULL,
  `tired_eyes` TINYINT(1) NOT NULL,
  INDEX `fk_user_contact_lens1_idx` (`contact_lens_id` ASC),
  PRIMARY KEY (`user_id`),
  CONSTRAINT `fk_user_contact_lens100`
    FOREIGN KEY (`contact_lens_id`)
    REFERENCES `ecpms-sd`.`contact_lens` (`contact_lens_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medical_history_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ecpms-sd`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`prescription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`prescription` (
  `record_id` INT NOT NULL,
  `d_od_sph` INT NULL,
  `d_od_cyl` INT NULL,
  `d_od_axis` INT NULL,
  `d_od_prism` INT NULL,
  `d_od_add` INT NULL,
  `d_os_sph` INT NULL,
  `d_os_cyl` INT NULL,
  `d_os_axis` INT NULL,
  `d_os_prism` INT NULL,
  `d_os_add` INT NULL,
  `n_od_sph` INT NULL,
  `n_od_cyl_cyl` INT NULL,
  `n_od_axis` INT NULL,
  `n_od_prism` INT NULL,
  `n_od_add` INT NULL,
  `n_os_sph` INT NULL,
  `n_os_cyl` INT NULL,
  `n_os_axis` INT NULL,
  `n_os_prism` INT NULL,
  `n_os_add` INT NULL,
  `design_id` INT NULL,
  `instruction_id` INT NULL,
  `od_bc` INT NULL,
  `od_diam` INT NULL,
  `od_power` INT NULL,
  `od_color` VARCHAR(45) NULL,
  `os_bc` INT NULL,
  `os_diam` INT NULL,
  `os_power` INT NULL,
  `os_color` VARCHAR(45) NULL,
  `wear_mode_id` INT NULL,
  `solutions_id` INT NULL,
  INDEX `fk_record_wear_mode1_idx` (`wear_mode_id` ASC),
  INDEX `fk_record_solutions1_idx` (`solutions_id` ASC),
  INDEX `fk_record_design1_idx` (`design_id` ASC),
  INDEX `fk_record_instruction1_idx` (`instruction_id` ASC),
  PRIMARY KEY (`record_id`),
  CONSTRAINT `fk_record_wear_mode10`
    FOREIGN KEY (`wear_mode_id`)
    REFERENCES `ecpms-sd`.`wear_mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_solutions10`
    FOREIGN KEY (`solutions_id`)
    REFERENCES `ecpms-sd`.`solutions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_design10`
    FOREIGN KEY (`design_id`)
    REFERENCES `ecpms-sd`.`design` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_record_instruction10`
    FOREIGN KEY (`instruction_id`)
    REFERENCES `ecpms-sd`.`instruction` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prescription_record1`
    FOREIGN KEY (`record_id`)
    REFERENCES `ecpms-sd`.`record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`evaluation` (
  `record_id` INT NOT NULL,
  `color_test` VARCHAR(45) NULL,
  `stereo_w4d` VARCHAR(45) NULL,
  `confrontation_avf` VARCHAR(45) NULL,
  `gross_exam` LONGTEXT NULL,
  `diagnostic_result` LONGTEXT NULL,
  `management` LONGTEXT NULL,
  `plan_TCB` LONGTEXT NULL,
  `plan_next_visit` DATE NULL,
  `v_d_od_sc` INT NULL,
  `v_d_od_cc` INT NULL,
  `v_d_od_ph` INT NULL,
  `v_n_od_sc` INT NULL,
  `v_n_od_cc` INT NULL,
  `v_d_os_sc` INT NULL,
  `v_d_os_cc` INT NULL,
  `v_d_os_ph` INT NULL,
  `v_n_os_sc` INT NULL,
  `v_n_os_cc` INT NULL,
  `v_d_ou_sc` INT NULL,
  `v_d_ou_cc` INT NULL,
  `v_d_ou_ph` INT NULL,
  `v_n_ou_sc` INT NULL,
  `v_n_ou_cc` INT NULL,
  `r_a_od` DECIMAL(5,2) NULL,
  `r_a_os` DECIMAL(5,2) NULL,
  `r_m_od` DECIMAL(5,2) NULL,
  `r_m_os` DECIMAL(5,2) NULL,
  `r_c_od` DECIMAL(5,2) NULL,
  `r_c_os` DECIMAL(5,2) NULL,
  `r_o_od` DECIMAL(5,2) NULL,
  `r_o_os` DECIMAL(5,2) NULL,
  `r_w_od` DECIMAL(5,2) NULL,
  `r_w_os` DECIMAL(5,2) NULL,
  `k_v_od` INT NULL,
  `k_v_os` INT NULL,
  `k_c_od` INT NULL,
  `k_c_os` INT NULL,
  `k_a_od` INT NULL,
  `k_a_os` INT NULL,
  `k_h_od` INT NULL,
  `k_h_os` INT NULL,
  `t_od` INT NULL,
  `t_os` INT NULL,
  `p_d_l` INT NULL,
  `p_d_v` INT NULL,
  `p_n_l` INT NULL,
  `p_n_v` INT NULL,
  `p_d_bi` INT NULL,
  `p_d_lbu` INT NULL,
  `p_n_bi` INT NULL,
  `p_n_lbu` INT NULL,
  `p_d_bo` INT NULL,
  `p_d_lbo` INT NULL,
  `p_n_bo` INT NULL,
  `p_n_lbo` INT NULL,
  `bp_s` INT NULL,
  `bp_d` INT NULL,
  `pupil_p_od` VARCHAR(1) NULL,
  `pupil_p_os` VARCHAR(1) NULL,
  `pupil_s_od` VARCHAR(1) NULL,
  `pupil_s_os` VARCHAR(1) NULL,
  `pupil_rapd` VARCHAR(1) NULL,
  `eoms_id` INT NOT NULL,
  `m_dominant` VARCHAR(45) NULL,
  `m_other` VARCHAR(45) NULL,
  `m_p_accom` INT NULL,
  `m_a_accom` INT NULL,
  `m_p_conver_num` INT NULL,
  `m_p_conver_den` INT NULL,
  `ee_lids_od` VARCHAR(45) NULL,
  `ee_lids_os` VARCHAR(45) NULL,
  `ee_c_od` VARCHAR(45) NULL,
  `ee_c_os` VARCHAR(45) NULL,
  `ee_d_od` VARCHAR(45) NULL,
  `ee_d_os` VARCHAR(45) NULL,
  `ee_l_od` VARCHAR(45) NULL,
  `ee_l_os` VARCHAR(45) NULL,
  `ee_t_od` VARCHAR(45) NULL,
  `ee_t_os` VARCHAR(45) NULL,
  `ee_s_od` VARCHAR(45) NULL,
  `ee_s_os` VARCHAR(45) NULL,
  `ee_od` LONGBLOB NULL,
  `ee_os` LONGBLOB NULL,
  `se_c_od` VARCHAR(45) NULL,
  `se_c_os` VARCHAR(45) NULL,
  `se_a_od` VARCHAR(45) NULL,
  `se_a_os` VARCHAR(45) NULL,
  `se_i_od` VARCHAR(45) NULL,
  `se_i_os` VARCHAR(45) NULL,
  `se_l_od` VARCHAR(45) NULL,
  `se_l_os` VARCHAR(45) NULL,
  `se_v_od` VARCHAR(45) NULL,
  `se_v_os` VARCHAR(45) NULL,
  `se_od` LONGBLOB NULL,
  `se_os` LONGBLOB NULL,
  `f_me_od` INT NULL,
  `f_me_os` INT NULL,
  `f_d_od` INT NULL,
  `f_d_os` INT NULL,
  `f_c_od` INT NULL,
  `f_c_os` INT NULL,
  `f_v_od` VARCHAR(45) NULL,
  `f_v_os` VARCHAR(45) NULL,
  `f_p_od` VARCHAR(45) NULL,
  `f_p_os` VARCHAR(45) NULL,
  `f_ma_od` VARCHAR(45) NULL,
  `f_m_os` VARCHAR(45) NULL,
  PRIMARY KEY (`record_id`),
  INDEX `fk_evaluation_eoms1_idx` (`eoms_id` ASC),
  CONSTRAINT `fk_evaluation_record1`
    FOREIGN KEY (`record_id`)
    REFERENCES `ecpms-sd`.`record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluation_eoms1`
    FOREIGN KEY (`eoms_id`)
    REFERENCES `ecpms-sd`.`eoms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ecpms-sd`.`accounting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecpms-sd`.`accounting` (
  `record_id` INT NOT NULL,
  `professional_fee` DECIMAL(7,2) NULL,
  `frames_price` DECIMAL(7,2) NULL,
  `lenses_price` DECIMAL(7,2) NULL,
  `contacts_price` DECIMAL(7,2) NULL,
  `solutions_price` DECIMAL(7,2) NULL,
  `ancilliary_procedures` DECIMAL(7,2) NULL,
  `others` DECIMAL(7,2) NULL,
  `insurance_id` INT NULL,
  `senior_citizen` DECIMAL(7,2) NULL,
  `person_w_disability` DECIMAL(7,2) NULL,
  `total` DECIMAL(10,2) NULL,
  `deposit` DECIMAL(10,2) NULL,
  `balance` DECIMAL(10,2) NULL,
  PRIMARY KEY (`record_id`),
  INDEX `fk_accounting_insurance1_idx` (`insurance_id` ASC),
  CONSTRAINT `fk_accounting_record1`
    FOREIGN KEY (`record_id`)
    REFERENCES `ecpms-sd`.`record` (`record_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_insurance1`
    FOREIGN KEY (`insurance_id`)
    REFERENCES `ecpms-sd`.`insurance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
